# **TikTok Project**
**Course 3 - The Power of Statistics**

**Author:** Ahmad Daniel  
**Date:** May 2026

You are a data professional at TikTok. The current project is reaching its midpoint; a project proposal, Python coding work, and exploratory data analysis have all been completed.

The team has reviewed the results of the exploratory data analysis and the previous executive summary the team prepared. You received an email from Orion Rainier, Data Scientist at TikTok, with your next assignment: determine and conduct the necessary hypothesis tests and statistical analysis for the TikTok classification project.

A notebook was structured and prepared to help you in this project. Please complete the following questions.

# **Course 3 End-of-course project: Data exploration and hypothesis testing**

In this activity, you will explore the data provided and conduct a hypothesis testing.

**The purpose** of this project is to demonstrate knowledge of how to prepare, create, and analyze hypothesis tests.

**The goal** is to apply descriptive and inferential statistics, probability distributions, and hypothesis testing in Python.

*This activity has three parts:*

**Part 1:** Imports and data loading
* What data packages will be necessary for hypothesis testing?

**Part 2:** Conduct hypothesis testing
* How will descriptive statistics help you analyze your data?
* How will you formulate your null hypothesis and alternative hypothesis?

**Part 3:** Communicate insights with stakeholders
* What key business insight(s) emerge from your hypothesis test?
* What business recommendations do you propose based on your results?

# **Data exploration and hypothesis testing**

## **PACE: Plan**

Consider the questions in your PACE Strategy Document and those below to craft your response.

1. What is your research question for this data project? Later on, you will need to formulate the null and alternative hypotheses as the first step of your hypothesis test. Consider your research question now, at the start of this task.

**Response:**

There are a few possible ways to frame the research question. For example:

1. Do videos from verified accounts and videos from unverified accounts have different average view counts?

2. Is there a relationship between the account being verified and the associated videos' view counts?

### **Task 1. Imports and Data Loading**

Import packages and libraries needed to compute descriptive statistics and conduct a hypothesis test.

In [21]:
# Import packages for data manipulation
import pandas as pd
import numpy as np

# Import packages for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Import packages for statistical analysis/hypothesis testing
from scipy import stats

In [22]:
# Load dataset into dataframe
data = pd.read_csv("tiktok_dataset.csv")

## **PACE: Analyze and Construct**

Consider the questions in your PACE Strategy Document and those below to craft your response:

1. Data professionals use descriptive statistics for Exploratory Data Analysis. How can computing descriptive statistics help you learn more about your data in this stage of your analysis?

**Response:**

In general, descriptive statistics are useful because they let you quickly explore and understand large amounts of data. In this case, computing descriptive statistics helps you quickly compute the mean values of `video_view_count` for each group of `verified_status` in the sample data.

### **Task 2. Data exploration**

Use descriptive statistics to conduct Exploratory Data Analysis (EDA).

Inspect the first five rows of the dataframe.

In [23]:
# Display first few rows
data.head()

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
0,1,claim,8762575920,14,someone shared with me that an average human c...,not verified,under scrutiny,587292.0,53354.0,16958.0,812.0,234.0
1,2,claim,3611525817,59,someone shared with me that microbes from the ...,not verified,active,785464.0,156452.0,616.0,2878.0,1852.0
2,3,claim,5070975780,11,someone shared with me that 20% of the world's...,not verified,banned,999949.0,562158.0,35841.0,445.0,236.0
3,4,claim,7233352528,50,someone shared with me that the number of busi...,not verified,active,365084.0,49164.0,6122.0,372.0,25.0
4,5,claim,3387873230,55,someone shared with me that the total number o...,verified,active,672207.0,203409.0,57134.0,4253.0,1253.0

In [24]:
# Generate a table of descriptive statistics about the data
data.describe()

,#,video_id,video_duration_sec,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
count,19382.000000,1.938200e+04,19382.000000,19182.000000,19182.000000,19182.000000,19182.000000,19182.000000
mean,9691.500000,5.605640e+09,32.455061,253763.179856,83234.815243,16522.990929,1034.953498,341.892138
std,5595.245794,2.530172e+09,16.155484,320836.905107,131588.832099,31720.266661,1992.411530,776.994082
min,1.000000,1.234730e+09,5.000000,21.000000,0.000000,0.000000,0.000000,0.000000
25%,4846.250000,3.421425e+09,18.250000,4966.000000,836.250000,118.000000,7.000000,1.000000
50%,9691.500000,5.595368e+09,32.000000,9980.500000,3531.500000,742.000000,47.000000,10.000000
75%,14536.750000,7.798543e+09,46.000000,502163.000000,123078.000000,18042.000000,1141.750000,278.000000
max,19382.000000,9.999935e+09,60.000000,999976.000000,656081.000000,239681.000000,15278.000000,7887.000000

Check for and handle missing values.

In [25]:
# Check for missing values
data.isna().sum()

#                             0
claim_status                200
video_id                      0
video_duration_sec            0
video_transcription_text    200
verified_status               0
author_ban_status             0
video_view_count            200
video_like_count            200
video_share_count           200
video_download_count        200
video_comment_count         200
dtype: int64

In [26]:
# Drop rows with missing values
data = data.dropna(axis=0)

In [27]:
# Display first few rows after handling missing values
data.head()

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
0,1,claim,8762575920,14,someone shared with me that an average human c...,not verified,under scrutiny,587292.0,53354.0,16958.0,812.0,234.0
1,2,claim,3611525817,59,someone shared with me that microbes from the ...,not verified,active,785464.0,156452.0,616.0,2878.0,1852.0
2,3,claim,5070975780,11,someone shared with me that 20% of the world's...,not verified,banned,999949.0,562158.0,35841.0,445.0,236.0
3,4,claim,7233352528,50,someone shared with me that the number of busi...,not verified,active,365084.0,49164.0,6122.0,372.0,25.0
4,5,claim,3387873230,55,someone shared with me that the total number o...,verified,active,672207.0,203409.0,57134.0,4253.0,1253.0

You are interested in the relationship between `verified_status` and `video_view_count`. One approach is to examine the mean values of `video_view_count` for each group of `verified_status` in the sample data.

In [28]:
# Compute the mean `video_view_count` for each group in `verified_status`
data.groupby("verified_status")["video_view_count"].mean()

verified_status
not verified    264331.906862
verified         88808.684848
Name: video_view_count, dtype: float64

### **Task 3. Hypothesis testing**

Before you conduct your hypothesis test, consider the following questions where applicable to complete your code response:

1. Recall the difference between the null hypothesis and the alternative hypotheses. What are your hypotheses for this data project?

**Response:**

* **Null hypothesis**: There is no difference in number of views between TikTok videos posted by verified accounts and TikTok videos posted by unverified accounts (any observed difference in the sample data is due to chance or sampling variability).
* **Alternative hypothesis**: There is a difference in number of views between TikTok videos posted by verified accounts and TikTok videos posted by unverified accounts (any observed difference in the sample data is due to an actual difference in the corresponding population means).

Your goal in this step is to conduct a two-sample t-test. Recall the steps for conducting a hypothesis test:

1. State the null hypothesis and the alternative hypothesis
2. Choose a significance level
3. Find the p-value
4. Reject or fail to reject the null hypothesis

**$H_0$**: There is no difference in number of views between TikTok videos posted by verified accounts and TikTok videos posted by unverified accounts (any observed difference in the sample data is due to chance or sampling variability).

**$H_A$**: There is a difference in number of views between TikTok videos posted by verified accounts and TikTok videos posted by unverified accounts (any observed difference in the sample data is due to an actual difference in the corresponding population means).

You choose 5% as the significance level and proceed with a two-sample t-test.

In [29]:
# Conduct a two-sample t-test to compare means

# Save each sample in a variable
not_verified = data[data["verified_status"] == "not verified"]["video_view_count"]
verified = data[data["verified_status"] == "verified"]["video_view_count"]

# Implement a t-test using the two samples
stats.ttest_ind(a=not_verified, b=verified, equal_var=False)

TtestResult(statistic=np.float64(25.293935749297567), pvalue=np.float64(9.802734352476062e-118), df=np.float64(1489.8631191423426))

**Response:**

Since the p-value is extremely small (much smaller than the significance level of 5%), you reject the null hypothesis. You conclude that there **is** a statistically significant difference in the mean video view count between verified and unverified accounts on TikTok.

## **PACE: Execute**

Consider the questions in your PACE Strategy Document to reflect on the Execute stage.

### **Task 4. Communicate insights with stakeholders**

*What business insight(s) can you draw from the result of your hypothesis test?*

**Response:**

The analysis shows that there is a statistically significant difference in the average view counts between videos from verified accounts and videos from unverified accounts. This suggests there might be fundamental behavioral differences between these two groups of accounts.

It would be interesting to investigate the root cause of this behavioral difference. For example, do unverified accounts tend to post more clickbait-y videos? Or are unverified accounts associated with spam bots that help inflate view counts?

The next step will be to build a regression model on `verified_status`. A regression model is the natural next step because the end goal is to make predictions on claim status. A regression model for `verified_status` can help analyze user behavior in this group of verified users. Technical note to prepare regression model: because the data is skewed, and there is a significant difference in account types, it will be key to build a **logistic regression model**.